name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'doc.md'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install Tex Live (includes pdflatex)
      run: |
        sudo apt-get install -y texlive

    - name: Convert Markdown to PDF
      run: |
        pandoc doc.md -o doc.pdf

    - name: Commit PDF to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add doc.pdf
        git commit -m "Add generated PDF" || echo "No changes to commit"
        git push
